chore: Localize feature import to crate for circuit prover (#3502)
### Description
This PR resolves the build failure in
[`zksync_prover_job_processor`](https://github.com/matter-labs/zksync-era/tree/main/prover/crates/lib/prover_job_processor)
caused by the following error:
```
error[E0432]: unresolved import tokio::task::JoinHandle
   --> crates/lib/prover_job_processor/src/job_runner.rs:1:5
    |
1   | use tokio::task::JoinHandle;
    |     ^^^^^^^^^^^^^^^^^^^^^^^ no JoinHandle in task
```
The error occurred because `JoinHandle` was gated behind the `rt`
feature in Tokio, which was disabled. Enabling the feature resolves the
import and fixes the build.