fix: make `zk status prover` use the new prover table (#1044)
## What ❔

Changed all usages of `prover_protocol_versions` to
`prover_fri_protocol_versions`, since the table got renamed

## Why ❔

`zk status prover` is broken:

```
$ zk status prover                                                                                                                                                                   19:04:27
==== FRI Prover Status ====
State keeper: First batch: 0, recent batch: 1
L1 state: block verified: 0, block committed: 1
Verification key hash on contract is 0x8574e152c41dc39a2ecab984545e1cf21cb3ec250b919018a8053f2fa270784f
Error: relation "prover_protocol_versions" does not exist
```

## Checklist

<!-- Check your PR fulfills the following items. -->
<!-- For draft PRs check the boxes as you complete them. -->

- [x] PR title corresponds to the body of PR (we generate changelog
entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [x] Code has been formatted via `zk fmt` and `zk lint`.
- [x] Spellcheck has been run via `zk spellcheck`.
- [x] Linkcheck has been run via `zk linkcheck`.